apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-checkout
  labels:
    {{- include "otel-demo.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "otel-demo.selectorLabels" (dict "name" "checkout" "root" .) | nindent 4 }}
  ports:
    - port: {{ .Values.checkout.port }}
      targetPort: {{ .Values.checkout.port }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-checkout
  labels:
    {{- include "otel-demo.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.checkout.replicas }}
  selector:
    matchLabels:
      {{- include "otel-demo.selectorLabels" (dict "name" "checkout" "root" .) | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "otel-demo.selectorLabels" (dict "name" "checkout" "root" .) | nindent 8 }}
    spec:
      containers:
        - name: checkout
          image: {{ include "otel-demo.image" (dict "img" .Values.images.checkout) }}
          imagePullPolicy: {{ .Values.images.checkout.pullPolicy }}
          ports:
            - containerPort: {{ .Values.checkout.port }}
          env:
            - name: OTEL_SERVICE_NAME
              value: checkout
            - name: POSTGRES_DB
              value: checkout_orders
            {{- include "otel-demo.otelEnv" . | nindent 12 }}
          resources:
            {{- toYaml .Values.checkout.resources | nindent 12 }}
          readinessProbe:
            exec:
              command: ["/app/grpc_health_probe", "-addr=localhost:{{ .Values.checkout.port }}"]
            initialDelaySeconds: 10
            periodSeconds: 5
