apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-payment
  labels:
    {{- include "otel-demo.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "otel-demo.selectorLabels" (dict "name" "payment" "root" .) | nindent 4 }}
  ports:
    - port: {{ .Values.payment.port }}
      targetPort: {{ .Values.payment.port }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-payment
  labels:
    {{- include "otel-demo.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.payment.replicas }}
  selector:
    matchLabels:
      {{- include "otel-demo.selectorLabels" (dict "name" "payment" "root" .) | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "otel-demo.selectorLabels" (dict "name" "payment" "root" .) | nindent 8 }}
    spec:
      containers:
        - name: payment
          image: {{ include "otel-demo.image" (dict "img" .Values.images.payment) }}
          imagePullPolicy: {{ .Values.images.payment.pullPolicy }}
          ports:
            - containerPort: {{ .Values.payment.port }}
          env:
            - name: OTEL_SERVICE_NAME
              value: payment
            {{- include "otel-demo.otelEnv" . | nindent 12 }}
          resources:
            {{- toYaml .Values.payment.resources | nindent 12 }}
          readinessProbe:
            exec:
              command: ["/app/grpc_health_probe", "-addr=localhost:{{ .Values.payment.port }}"]
            initialDelaySeconds: 3
            periodSeconds: 5
