apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-product-catalog
  labels:
    {{- include "otel-demo.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "otel-demo.selectorLabels" (dict "name" "product-catalog" "root" .) | nindent 4 }}
  ports:
    - port: {{ .Values.productCatalog.port }}
      targetPort: {{ .Values.productCatalog.port }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-product-catalog
  labels:
    {{- include "otel-demo.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.productCatalog.replicas }}
  selector:
    matchLabels:
      {{- include "otel-demo.selectorLabels" (dict "name" "product-catalog" "root" .) | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "otel-demo.selectorLabels" (dict "name" "product-catalog" "root" .) | nindent 8 }}
    spec:
      containers:
        - name: product-catalog
          image: {{ include "otel-demo.image" (dict "img" .Values.images.productCatalog) }}
          imagePullPolicy: {{ .Values.images.productCatalog.pullPolicy }}
          ports:
            - containerPort: {{ .Values.productCatalog.port }}
          env:
            - name: OTEL_SERVICE_NAME
              value: product-catalog
            - name: POSTGRES_DB
              value: product_catalog
            {{- include "otel-demo.otelEnv" . | nindent 12 }}
          resources:
            {{- toYaml .Values.productCatalog.resources | nindent 12 }}
          readinessProbe:
            exec:
              command: ["/app/grpc_health_probe", "-addr=localhost:{{ .Values.productCatalog.port }}"]
            initialDelaySeconds: 5
            periodSeconds: 5
