apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-valkey
  labels:
    {{- include "otel-demo.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "otel-demo.selectorLabels" (dict "name" "valkey" "root" .) | nindent 4 }}
  ports:
    - port: 6379
      targetPort: 6379
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-valkey
  labels:
    {{- include "otel-demo.labels" . | nindent 4 }}
spec:
  serviceName: {{ .Release.Name }}-valkey
  replicas: {{ .Values.valkey.replicas }}
  selector:
    matchLabels:
      {{- include "otel-demo.selectorLabels" (dict "name" "valkey" "root" .) | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "otel-demo.selectorLabels" (dict "name" "valkey" "root" .) | nindent 8 }}
    spec:
      containers:
        - name: valkey
          image: {{ .Values.valkey.image }}
          command: ["valkey-server", "--save", "", "--appendonly", "no", "--maxmemory", "16mb", "--maxmemory-policy", "allkeys-lru"]
          ports:
            - containerPort: 6379
          resources:
            {{- toYaml .Values.valkey.resources | nindent 12 }}
          readinessProbe:
            exec:
              command: ["valkey-cli", "ping"]
            initialDelaySeconds: 3
            periodSeconds: 5
