apiVersion: v1
kind: Service
metadata:
  name: cart
spec:
  selector:
    app: cart
  ports:
    - port: 7070
      targetPort: 7070
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cart
  template:
    metadata:
      labels:
        app: cart
    spec:
      containers:
        - name: cart
          image: otel-demo-light/cart:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 7070
          envFrom:
            - configMapRef:
                name: shared-env
          env:
            - name: OTEL_SERVICE_NAME
              value: cart
            - name: JAVA_TOOL_OPTIONS
              value: "-javaagent:/app/opentelemetry-javaagent.jar -Xmx128m"
          resources:
            limits:
              memory: 200Mi
            requests:
              memory: 100Mi
          readinessProbe:
            exec:
              command: ["/app/grpc_health_probe", "-addr=localhost:7070"]
            initialDelaySeconds: 15
            periodSeconds: 5
