apiVersion: v1
kind: Service
metadata:
  name: checkout
spec:
  selector:
    app: checkout
  ports:
    - port: 5050
      targetPort: 5050
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: checkout
spec:
  replicas: 1
  selector:
    matchLabels:
      app: checkout
  template:
    metadata:
      labels:
        app: checkout
    spec:
      containers:
        - name: checkout
          image: otel-demo-light/checkout:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5050
          envFrom:
            - configMapRef:
                name: shared-env
          env:
            - name: OTEL_SERVICE_NAME
              value: checkout
            - name: POSTGRES_DB
              value: checkout_orders
          resources:
            limits:
              memory: 50Mi
            requests:
              memory: 25Mi
          readinessProbe:
            exec:
              command: ["/app/grpc_health_probe", "-addr=localhost:5050"]
            initialDelaySeconds: 10
            periodSeconds: 5
