apiVersion: apps/v1
kind: Deployment
metadata:
  name: load-generator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: load-generator
  template:
    metadata:
      labels:
        app: load-generator
    spec:
      containers:
        - name: load-generator
          image: ghcr.io/henrikrexed/opentelemetry-demo-light/load-generator:latest
          env:
            - name: FRONTEND_URL
              value: http://frontend:8080
            - name: K6_VUS
              value: "5"
            - name: K6_DURATION
              value: "0"
            - name: K6_OUTPUT_MODE
              value: opentelemetry
            - name: K6_OTEL_GRPC_EXPORTER_INSECURE
              value: "true"
            - name: K6_OTEL_EXPORTER_OTLP_ENDPOINT
              value: http://otel-collector:4317
            - name: OTEL_SERVICE_NAME
              value: load-generator
          resources:
            limits:
              memory: 128Mi
            requests:
              memory: 64Mi
          volumeMounts:
            - name: test-script
              mountPath: /scripts/test.js
              subPath: test.js
      volumes:
        - name: test-script
          configMap:
            name: k6-test-script
