apiVersion: v1
kind: Service
metadata:
  name: payment
spec:
  selector:
    app: payment
  ports:
    - port: 6060
      targetPort: 6060
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment
  template:
    metadata:
      labels:
        app: payment
    spec:
      containers:
        - name: payment
          image: otel-demo-light/payment:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 6060
          envFrom:
            - configMapRef:
                name: shared-env
          env:
            - name: OTEL_SERVICE_NAME
              value: payment
          resources:
            limits:
              memory: 10Mi
            requests:
              memory: 5Mi
          readinessProbe:
            exec:
              command: ["/app/grpc_health_probe", "-addr=localhost:6060"]
            initialDelaySeconds: 3
            periodSeconds: 5
