apiVersion: v1
kind: Service
metadata:
  name: product-catalog
spec:
  selector:
    app: product-catalog
  ports:
    - port: 3550
      targetPort: 3550
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-catalog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-catalog
  template:
    metadata:
      labels:
        app: product-catalog
    spec:
      containers:
        - name: product-catalog
          image: otel-demo-light/product-catalog:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3550
          envFrom:
            - configMapRef:
                name: shared-env
          env:
            - name: OTEL_SERVICE_NAME
              value: product-catalog
            - name: POSTGRES_DB
              value: product_catalog
          resources:
            limits:
              memory: 20Mi
            requests:
              memory: 10Mi
          readinessProbe:
            exec:
              command: ["/app/grpc_health_probe", "-addr=localhost:3550"]
            initialDelaySeconds: 5
            periodSeconds: 5
